// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

/**
 * ESLint for the Nuxt boilerplate.
 *
 * The base config is generated by `@nuxt/eslint` (see `nuxt.config.ts`) because
 * it is the only thing that knows Nuxt's auto-imports — without it every
 * `useRoute`, `defineNuxtPlugin`, `$fetch` and `navigateTo` reads as an
 * undefined global. It is written into `.nuxt/` by `nuxt prepare`, which
 * `postinstall` already runs, so a fresh clone can lint after `npm install`.
 *
 * This app had no linting before, so the first run reports a backlog rather
 * than a regression. Errors are what the compiler cannot see — `vue-tsc` never
 * looks inside a template, so an undefined component, a missing `:key` or a
 * mutated prop builds green and fails at runtime. The `any` and unused-symbol
 * findings are warnings: a real backlog, but not a reason to fail a build that
 * was green yesterday.
 */
export default withNuxt({
  ignores: [
    'dist/**',
    '.output/**',
    '.nuxt/**',
    'node_modules/**',
    // Generated by predev/prebuild and gitignored.
    'app/locales/_registry.ts',
  ],
}).append({
  files: ['**/*.{js,mjs,ts,tsx,vue}'],
  rules: {
    // Underscore-prefixed names are the conventional "declared on purpose,
    // deliberately unused" marker. `ignoreRestSiblings` covers the
    // omit-by-destructuring idiom (`const { a: _a, ...rest } = x`), where the
    // named keys exist precisely so `rest` does not contain them.
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    '@typescript-eslint/no-explicit-any': 'warn',

    // `delete obj[key]` on an object we just copied (`const next = {...x};
    // delete next[path]`) is the clearest way to drop one entry from a record
    // keyed by a runtime string. The rule is a de-optimisation warning, not a
    // correctness one, and the alternatives (a rest-destructure with a
    // computed key, or a filtered `Object.entries` rebuild) are longer and
    // read worse.
    '@typescript-eslint/no-dynamic-delete': 'off',
  },
}).append({
  files: ['**/*.vue'],
  rules: {
    // False positives only. The rule guards against Vue 2's `{{ x | filter }}`
    // syntax, which Vue 3 removed outright — but its parser also reads the `|`
    // in a TypeScript union assertion as a filter pipe, so
    // `:cart="cartStore.cart as Cart | null"` is reported as a deprecated
    // filter. Every hit in this app is such a cast, and a genuine Vue 2 filter
    // would not render at all in Vue 3, so the rule has nothing left to catch.
    'vue/no-deprecated-filter': 'off',

    // Formatting, and formatting this codebase deliberately does differently.
    // Template attributes are written in camelCase to match the prop names the
    // `propeller-v2-vue-ui` package declares (`:machineCardLabels`,
    // `:onListingChange`), which is also how propeller-vue and propeller-next
    // spell them. Honouring the rule would rewrite 555 attributes across the
    // app, change nothing at runtime, and leave the three stacks inconsistent.
    'vue/attribute-hyphenation': 'off',
    'vue/attributes-order': 'off',
    'vue/html-self-closing': 'off',
  },
});
